cmake_minimum_required(VERSION 3.12)
project(YACE)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_compile_options(-Wall -Wextra -Wpedantic)
include_directories(${CMAKE_SOURCE_DIR}/include)
find_package(SDL2 REQUIRED)
include_directories(${SDL2_INCLUDE_DIRS})
set(SOURCES src/main.c src/chip8.c src/display.c src/keypad.c)
add_executable(YACE ${SOURCES})
target_link_libraries(YACE PRIVATE ${SDL2_LIBRARIES})